// 服务配置 — 给可视化后台看 / 改的"运行期 + .env"两类配置
import { Hono } from 'hono';
import { zValidator } from '@hono/zod-validator';
import {
  AdminConfigEnvPatchSchema,
  AdminConfigRuntimePatchSchema,
  AdminConfigTestLLMSchema,
  AdminImageConfigSchema,
  DEFAULT_GLOBAL_BOUNDARY,
} from '@yelan/shared';
import { existsSync, readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import { store } from '../../store/persistence';
import { audit } from './_audit';
import { getRouter, resetRouter } from '../../llm/create-router';
import { getClientFlags } from '../../config/feature-flags';
import { validationHook } from '../../middleware/validation';
import { requireAdmin } from '../../middleware/auth';
import { publicImageConfig, saveImageConfig } from '../../services/image-config';

export const adminConfigRoute = new Hono();
adminConfigRoute.use('/image', requireAdmin());
adminConfigRoute.get('/image', c => { c.header('Cache-Control', 'private, no-store'); return c.json(publicImageConfig()); });
adminConfigRoute.put('/image', zValidator('json', AdminImageConfigSchema, validationHook), c => {
  const input = c.req.valid('json');
  const result = saveImageConfig(input);
  audit('config.image', undefined, undefined, { enabled: input.enabled, keyChanged: Boolean(input.apiKey) });
  c.header('Cache-Control', 'private, no-store');
  return c.json(result);
});

const here = dirname(fileURLToPath(import.meta.url));
const ENV_FILE = resolve(here, '..', '..', '..', '.env');

function mask(value: string | undefined): string {
  if (!value) return '';
  if (value.length <= 10) return '****';
  return `${value.slice(0, 4)}…${value.slice(-4)}`;
}

const ENV_KEYS = {
  llm: [
    'ANTHROPIC_API_KEY', 'ANTHROPIC_MODEL',
    'OPENAI_API_KEY', 'OPENAI_BASE_URL', 'OPENAI_MODEL',
    'DEEPSEEK_API_KEY', 'DEEPSEEK_BASE_URL', 'DEEPSEEK_MODEL',
    'SIDECAR_TASK_API_KEY', 'SIDECAR_TASK_BASE_URL', 'SIDECAR_TASK_MODEL',
    'NVIDIA_API_KEY', 'UNLIM_WORKER_URL',
  ],
  policy: ['NARRATIVE_BOUNDARY_GLOBAL', 'FEATURE_TEMP_V2', 'ADMIN_TOKEN'],
  storage: ['DATABASE_URL', 'REDIS_URL'],
  pay: ['WECHAT_PAY_MCH_ID', 'WECHAT_PAY_KEY', 'ALIPAY_APP_ID', 'ALIPAY_PRIVATE_KEY', 'STRIPE_SECRET_KEY'],
  observability: ['SENTRY_DSN_SERVER'],
  mock: ['MOCK_PORT', 'MOCK_LATENCY_MS'],
} as const;

const SECRET_KEYS = new Set([
  'ANTHROPIC_API_KEY', 'OPENAI_API_KEY', 'DEEPSEEK_API_KEY',
  'NVIDIA_API_KEY', 'SIDECAR_TASK_API_KEY', 'WECHAT_PAY_KEY', 'ALIPAY_PRIVATE_KEY',
  'STRIPE_SECRET_KEY', 'ADMIN_TOKEN', 'DATABASE_URL', 'REDIS_URL',
  'SENTRY_DSN_SERVER',
]);

adminConfigRoute.get('/', (c) => {
  const groups: Record<string, Array<{ key: string; value: string; present: boolean; secret: boolean }>> = {};
  for (const [group, keys] of Object.entries(ENV_KEYS)) {
    groups[group] = keys.map((k) => {
      const v = process.env[k] ?? '';
      const secret = SECRET_KEYS.has(k);
      return { key: k, value: secret ? mask(v) : v, present: !!v, secret };
    });
  }

  const router = getRouter();
  return c.json({
    env: groups,
    runtime: {
      narrativeBoundaryGlobal: Number(process.env.NARRATIVE_BOUNDARY_GLOBAL ?? DEFAULT_GLOBAL_BOUNDARY),
      mockLatencyMs: Number(process.env.MOCK_LATENCY_MS ?? 120),
      freeLimitOverride: store.state().freeLimitOverride,
    },
    llm: {
      hasReady: router.hasReady(),
      providers: Array.from(router.providers.entries()).map(([name, p]) => ({ name, ready: p.ready })),
    },
    featureFlags: getClientFlags(),
  });
});

adminConfigRoute.post(
  '/env',
  zValidator('json', AdminConfigEnvPatchSchema, validationHook),
  async (c) => {
    const body = c.req.valid('json');
    const current = new Map<string, string>();
    if (existsSync(ENV_FILE)) {
      for (const line of readFileSync(ENV_FILE, 'utf8').split(/\r?\n/)) {
        const m = line.match(/^([A-Za-z_][\w]*)\s*=\s*(.*)$/);
        if (m) current.set(m[1]!, m[2]!);
      }
    }
    for (const [k, v] of Object.entries(body.patch)) {
      current.set(k, v);
      process.env[k] = v;
    }
    const lines = ['# AUTO-GENERATED by /api/admin/config/env'];
    for (const [k, v] of current.entries()) lines.push(`${k}=${v}`);
    if (!existsSync(dirname(ENV_FILE))) mkdirSync(dirname(ENV_FILE), { recursive: true });
    writeFileSync(ENV_FILE, lines.join('\n') + '\n', 'utf8');
    resetRouter();
    audit('config.env', undefined, body.reason, { keys: Object.keys(body.patch) });
    return c.json({ ok: true, patched: Object.keys(body.patch).length });
  },
);

adminConfigRoute.post(
  '/runtime',
  zValidator('json', AdminConfigRuntimePatchSchema, validationHook),
  async (c) => {
    const body = c.req.valid('json');
    if (body.narrativeBoundaryGlobal !== undefined) {
      process.env.NARRATIVE_BOUNDARY_GLOBAL = String(body.narrativeBoundaryGlobal);
    }
    if (body.mockLatencyMs !== undefined) {
      process.env.MOCK_LATENCY_MS = String(body.mockLatencyMs);
    }
    if (body.freeLimitOverride !== undefined) {
      store.state().freeLimitOverride = body.freeLimitOverride;
      store.save();
    }
    audit('config.runtime', undefined, body.reason, body);
    return c.json({ ok: true });
  },
);

adminConfigRoute.post(
  '/test-llm',
  zValidator('json', AdminConfigTestLLMSchema, validationHook),
  async (c) => {
    const { provider } = c.req.valid('json');
    const router = getRouter();
    const p = router.providers.get(provider);
    if (!p) return c.json({ ok: false, error: 'provider not found' }, 400);
    if (!p.ready) return c.json({ ok: false, error: 'API key missing' }, 400);
    try {
      const t0 = Date.now();
      const r = await p.complete({
        model: '',
        messages: [
          { role: 'system', content: '你是一个简短回答的中文助手' },
          { role: 'user', content: '回答一句话：今晚月色如何？' },
        ],
        maxTokens: 64,
      });
      return c.json({ ok: true, latencyMs: Date.now() - t0, sample: r.text });
    } catch (e) {
      return c.json({ ok: false, error: (e as Error).message }, 500);
    }
  },
);
