// 把 yaml/md 在构建期烘成 src/generated.ts
// 服务端运行时直接 import 字符串/对象，无需文件系统
import { readFileSync, readdirSync, writeFileSync, statSync, watch } from 'node:fs';
import { join, dirname, extname, basename } from 'node:path';
import { fileURLToPath } from 'node:url';
import yaml from 'js-yaml';

const here = dirname(fileURLToPath(import.meta.url));
const root = join(here, '..');

interface CharacterCard {
  id: string;
  name: string;
  rarity: string;
  price_candle: number;
  style_tags: string[];
  prompt_card_key: string;
  boundary_default: number;
  memory_policy: string;
  opening_lines: { first_visit: string; return_visit: string };
  description?: string;
  voice?: { pace?: string; formality?: string; forbidden_phrases?: string[] };
}

function loadDir(dir: string): Record<string, string> {
  const out: Record<string, string> = {};
  for (const file of readdirSync(dir)) {
    const full = join(dir, file);
    if (!statSync(full).isFile()) continue;
    const ext = extname(file);
    if (ext !== '.md' && ext !== '.yaml' && ext !== '.yml') continue;
    const slug = basename(file, ext);
    out[slug] = readFileSync(full, 'utf8');
  }
  return out;
}

function loadCharacters(dir: string): Record<string, CharacterCard> {
  const out: Record<string, CharacterCard> = {};
  for (const file of readdirSync(dir)) {
    if (!file.endsWith('.yaml') && !file.endsWith('.yml')) continue;
    const slug = basename(file, extname(file));
    const text = readFileSync(join(dir, file), 'utf8');
    out[slug] = yaml.load(text) as CharacterCard;
  }
  return out;
}

function generate() {
  const characters = loadCharacters(join(root, 'characters'));
  const strategies = loadDir(join(root, 'strategies'));
  const boundaries = loadDir(join(root, 'boundaries'));
  const systemTemplate = readFileSync(join(root, 'system.template.md'), 'utf8');

  const banner = `// AUTO-GENERATED by packages/prompts/scripts/build.ts — 不要手改。
// 来源: characters/*.yaml + strategies/*.md + boundaries/*.md + system.template.md
// 跑 \`pnpm --filter @yelan/prompts build\` 重新生成。
`;

  const body = `
export interface CharacterCard {
  id: string;
  name: string;
  rarity: 'free' | 'paid' | 'hidden';
  price_candle: number;
  style_tags: string[];
  prompt_card_key: string;
  boundary_default: 1 | 2 | 3 | 4 | 5;
  memory_policy: string;
  opening_lines: { first_visit: string; return_visit: string };
  description?: string;
  voice?: { pace?: string; formality?: string; forbidden_phrases?: string[] };
}

export const characters: Record<string, CharacterCard> = ${JSON.stringify(characters, null, 2)} as Record<string, CharacterCard>;

export const strategies: Record<string, string> = ${JSON.stringify(strategies, null, 2)};

export const boundaries: Record<string, string> = ${JSON.stringify(boundaries, null, 2)};

export const systemTemplate: string = ${JSON.stringify(systemTemplate)};

export const ASSET_VERSION = ${JSON.stringify(new Date().toISOString())};
`;

  const outPath = join(root, 'src', 'generated.ts');
  writeFileSync(outPath, banner + body);
  console.log(`✓ 生成 ${outPath}`);
  console.log(`  · ${Object.keys(characters).length} 个角色卡`);
  console.log(`  · ${Object.keys(strategies).length} 个 strategy`);
  console.log(`  · ${Object.keys(boundaries).length} 个 boundary`);
}

generate();

// --watch 模式给开发期用：改 yaml/md 自动重新生成
if (process.argv.includes('--watch')) {
  console.log('监听变更中...（Ctrl+C 退出）');
  const watchDirs = [join(root, 'characters'), join(root, 'strategies'), join(root, 'boundaries'), root];
  for (const d of watchDirs) {
    watch(d, { recursive: false }, (_event, filename) => {
      if (!filename) return;
      if (!/\.(yaml|yml|md)$/.test(filename)) return;
      try {
        generate();
      } catch (e) {
        console.error('[build error]', e);
      }
    });
  }
}
