// Browser-friendly form for the existing HTTP Basic preview gate.
// Credentials go only to the same-origin /__preview endpoint; nothing is persisted.
export function previewLogin() {
  const nonce = crypto.randomUUID();
  return new Response(`<!doctype html><html lang="zh-CN"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>夜阑 · 测试入口</title><style>body{background:#171715;color:#ede6d8;font:16px system-ui;margin:0;min-height:100vh;display:grid;place-items:center}form{width:min(320px,80vw)}h1{font-size:28px;font-weight:500}label{display:block;margin:20px 0 8px}input,button{box-sizing:border-box;width:100%;padding:12px;border-radius:6px;font:inherit}input{background:#242420;color:#ede6d8;border:1px solid #66645b}button{margin-top:24px;background:#e7dcc6;color:#171715;border:0;cursor:pointer}p{line-height:1.7;color:#b7b2a6}#message{color:#ecb2a1}</style><form id="login"><h1>夜阑测试入口</h1><p>服务仍在维护中。请使用已有的测试入口凭据。</p><label for="username">测试用户名</label><input id="username" autocomplete="off" required><label for="password">测试密码</label><input id="password" type="password" autocomplete="off" required><button>进入预览</button><p id="message" role="alert"></p></form><script nonce="${nonce}">document.getElementById('login').addEventListener('submit',async event=>{event.preventDefault();const button=document.querySelector('button');button.disabled=true;document.getElementById('message').textContent='';try{const text=document.getElementById('username').value+':'+document.getElementById('password').value;const bytes=new TextEncoder().encode(text);const auth=btoa(Array.from(bytes,b=>String.fromCharCode(b)).join(''));const response=await fetch('/__preview',{headers:{Authorization:'Basic '+auth},credentials:'same-origin',cache:'no-store'});document.getElementById('password').value='';if(!response.ok)throw Error(response.status===401?'用户名或密码不正确。':'暂时无法进入，请稍后重试。');location.replace('/');}catch(error){document.getElementById('message').textContent=error.message||'连接失败，请稍后重试。';button.disabled=false;}});</script></html>`, {headers:{
    'Content-Type':'text/html; charset=utf-8', 'Cache-Control':'private, no-store',
    'Referrer-Policy':'no-referrer', 'X-Content-Type-Options':'nosniff',
    'Content-Security-Policy':`default-src 'none'; script-src 'nonce-${nonce}'; style-src 'unsafe-inline'; connect-src 'self'; form-action 'self'; frame-ancestors 'none'; base-uri 'none'`,
  }});
}
